### ISSUE TITLE
Keep crazy swaps included in events_detected

### ISSUE THREAD

**Issue by straussed** [arianasp/move_comm_analysis#1]
I decided to use github functionality to store notes on improving things

For identify_splits_and_merges(), it would be good to keep the crazy swaps in the events_dected dataframe so that we can find them easily. For plotting examples for instance, it would be nice to be able to supply the event_idx for a crazy swap to plot it, but those events don't get an index. Even if the rest of the columns are undefined, it would be good to have those events included in the df

**Comment by arianasp** [comment]
Good idea re github issues.
I think the "shuffles" do get rows in that events_detected data frame. Can you check it again? They should get rows but with a lot of the columns having NAs.

**Comment by straussed** [comment]
Oh you are right! I only checked if there were dropped numbers, and I misremembered from our conversation that shuffles weren't in the df.
